/**
 * Hallucination Detector for ChaosSaga
 *
 * Scans LLM output for narrative patterns that imply state changes (gaining items,
 * finishing quests, etc.) which were NOT accompanied by actual tool calls.
 */

// Patterns that imply the player received something or status changed
const CLAIM_PATTERNS = [
  /获得(?:了)?\s*[:：]?\s*([^\s,，.。]+)/, // 获得了 [物品]
  /得到(?:了)?\s*[:：]?\s*([^\s,，.。]+)/, // 得到了 [物品]
  /购买(?:了)?\s*[:：]?\s*([^\s,，.。]+)/, // 购买了 [物品]
  /任务(?:已)?完成/,                    // 任务完成
  /接受(?:了)?委托/,                    // 接受委托
  /支付(?:了)?\s*\d+/,                 // 支付了 [金额]
  /扣除(?:了)?\s*\d+/,                 // 扣除了 [金额]
  /HP\s*恢复/,                         // HP 恢复
  /MP\s*恢复/,                         // MP 恢复
];

// Tools that are capable of changing state
const STATE_MODIFYING_TOOLS = new Set([
  'add_item',
  'interact_npc', // can buy/sell/heal
  'create_quest',
  'update_quest',
  'process_quest_rewards', // hypothetical, usually update_quest covers this
  'modify_player_data', // GM tool
  'use_item', // can heal
  'execute_battle_action', // yields loot/exp usually via internal logic, but prompts might hallmark it
]);

// Patterns specific to battle fabrication — only ACTION outcomes, not status descriptions.
// Note: AI often wraps numbers in Markdown bold (**-12**), so patterns account for ** wrappers.
// ⚠️ Do NOT add HP/MP status patterns (e.g. "HP 22/100") here — they match legitimate state descriptions.
const BATTLE_PATTERNS = [
  /HP\s*\*{0,2}[-+]\s*\d+\*{0,2}/,     // HP **-10**, HP +15 (damage/heal delta)
  /MP\s*\*{0,2}[-+]\s*\d+\*{0,2}/,     // MP **-5**, MP +10 (mana delta)
  /(?:击杀|消灭|打败|干掉)(?:了)?/,      // 击杀了...
  /战斗胜利/,                          // 战斗胜利
  /造成(?:了)?\s*\*{0,2}\d+\*{0,2}\s*点?伤害/, // 造成了 **10** 点伤害
];

/**
 * Detects if the narrative claims state changes that weren't backed by tools.
 * 
 * @param text The full narrative text generated by the LLM
 * @param calledTools The list of tool names called during this turn
 * @param isBattle Whether the game is currently in battle mode
 * @returns Object containing detection result and specific reason
 */
export function detectHallucinations(
  text: string, 
  calledTools: string[],
  isBattle: boolean = false
): { hasHallucination: boolean; reason?: string } {
  // If no text, no hallucination possible (or at least not of this type)
  if (!text) return { hasHallucination: false };

  // If any state-modifying tool was called, we assume the LLM *tried* to do the right thing.
  const hasModifyingTool = calledTools.some(t => STATE_MODIFYING_TOOLS.has(t));
  
  if (hasModifyingTool) {
    return { hasHallucination: false };
  }

  // 1. Scan for general item/quest patterns (always active)
  for (const pattern of CLAIM_PATTERNS) {
    const match = text.match(pattern);
    if (match) {
      return { 
        hasHallucination: true, 
        reason: `Detected phrase "${match[0]}" but no state-modifying tools were called.` 
      };
    }
  }

  // 2. Scan for battle-specific patterns (ONLY active in battle mode)
  if (isBattle) {
    for (const pattern of BATTLE_PATTERNS) {
      const match = text.match(pattern);
      if (match) {
        return { 
          hasHallucination: true, 
          reason: `[Battle Protocol Violation] Detected combat narrative "${match[0]}" without calling 'execute_battle_action'. You MUST use the tool for ALL battle actions.` 
        };
      }
    }
  }

  // 3. Scan for "Battle Start" patterns (Active in Exploration mode)
  // If the AI says "Battle Start" but didn't call start_battle, it's a hallucination.
  const BATTLE_START_PATTERNS = [
    /\[?战斗开始\]?/,          // [Battle Start]
    /战斗一触即发/,            // Battle imminent
    /无法逃避/,               // Cannot escape
    /遭遇(?:了)?\s*.*\s*袭/,   // Encountered ... attack
    /敌人.*出现/,             // Enemy ... appears
  ];

  const hasStartBattle = calledTools.includes('start_battle');
  // Only check if we are NOT in battle (or even if we are, re-starting is weird but less critical)
  
  for (const pattern of BATTLE_START_PATTERNS) {
      const match = text.match(pattern);
      if (match && !hasStartBattle && !isBattle) { // If already in battle, maybe describing reinforcements? But usually start_battle needed for new mobs.
        return {
            hasHallucination: true,
            reason: `[System Error] You described a battle starting ("${match[0]}") but DID NOT call the 'start_battle' tool. You must call 'start_battle' to spawn enemies.`
        };
      }
  }

  return { hasHallucination: false };
}
